### PR TITLE
producer

### PR DESCRIPTION
**Pull request by snoyberg**
This isn't ready to be merged yet, but I thought you might want to see what it would look like with the new producer branch of conduit.

### CODE REVIEW

**Comment by snoyberg** [comment]
OK, I'm about to release conduit, this should be ready for release.

**Comment by meteficha** [comment]
Merged and released!  @snoyberg, do you think that it would be easier for you if `crypto-conduit` was merged into `conduit`'s repo?  I don't have any problems with that =).

**Comment by snoyberg** [comment]
@meteficha It might be, but I don't want to steal your packages :). If, on the other hand, it's easier for _you_, then let's plan to do it next time there's a major version bump (which coincidentally, I hope == never).

**Comment by meteficha** [comment]
You wouldn't be stealing anything.  Besides, you already have commit access to this repo and my permission to release new versions of `crypto-conduit` anyway =).  Well, let's leave things as they are for now =).

**Pull request merged**
